project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: /public/locales/pt-BR/translation.json
    translation: /public/locales/%two_letters_code%/translation.json
